### ISSUE TITLE
Android 4.x Build Doubled in Size

### ISSUE THREAD

**Issue by dmarcs** [opencv/ci-gha-workflow#129]
If you compare the build artifacts from these 2 runs

1. https://github.com/opencv/ci-gha-workflow/actions/runs/6345578976
2. https://github.com/opencv/ci-gha-workflow/actions/runs/6425845547

The first is much bigger than the second. One big difference between the 2 is OpenCV-android-sdk/sdk/native/libs/x86_64/libopencv_java4.so

The size of libopencv_java4.so is the same for all other architectures (armeabi-v7a, arm64-v8a, x86). For whatever reason it only doubled in size for x86_64.

OpenCV-android-sdk/sdk/native/libs/x86_64/libopencv_java4.so should be around 26 MB, but it ends up being over 52 MB

**Comment by dmarcs** [comment]
The size difference is because the 2nd build includes ippiw and ippicv.

**Comment by opencv-alalek** [comment]
relates #115
